version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: lab1_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql

  api:
    image: lab1_rest_api
    build:
      context: .
      dockerfile: PRN232.LAB_1_REST_API.API/Dockerfile
    container_name: lab1_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=Lab1LmsDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    depends_on:
      - db

volumes:
  dbdata:
